server:
  port: 8763
spring:
 application:
  name: eureka-client
 datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/nts?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT
  username: root
  password: root

# 上传文件上限
servlet:
  multipart:
  max-file-size: 100MB
  max-request-size: 1000MB

#mybatis配置
mybatis:
  typeAliasesPackage: com.pratice.eurekaclient.Entity
  configLocation: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#\u65e5\u5fd7\u914d\u7f6e
#logging:
#  config: classpath:log4j2.yml
